### ISSUE TITLE
Add support for DEL-key

### ISSUE THREAD

**Issue by artemanufrij** [jurplel/qView#210]
Hey @jurplel,
could you add support for DEL-key, please?

It would be helpful for fast clean up of useless pictures after a photo shooting.

best regards

**Comment by jurplel** [comment]
Sure thing, I'll do it next version.

**Comment by pawel5** [comment]
I'm trying to add this now

**Comment by pawel5** [comment]
Well, I can't find the place where I could close the file so it's not used by app and I could delete it..

**Comment by artemanufrij** [comment]
@pawel5 
I would 
* remember the path of current image
* navigate to next image
* remove remembered path

**Comment by pawel5** [comment]
@artemanufrij this would work unless you get to the case when you have one file in directory. :) qView don't have any explicit way to close currently opened file and thus enable it's deletion, I am trying to implement it but can't find what is holding a file

**Comment by artemanufrij** [comment]
@jurplel have you an idea?

**Comment by jurplel** [comment]
I'm not quite sure what you can't find.

**Comment by pawel5** [comment]
What I'm trying to achieve is just remove file using QFile:
```C++
QFile::remove(ui->graphicsView->getCurrentFileDetails().fileInfo.filePath());
```
it doesn't work and returns false as file is opened in qView (or at least it works this way on Windows). What I don't know is what is holding this file and where could I free it.
According to docs `QImageReader` internally creates `QFile`, but after setting empty file name or even explicitly closing device file removing still don't work:
```C++
imageReader.setFileName("");
if(auto* device = imageReader.device())
    device->close();
```
I thought it might be held in cache, but it won't help either:
```C++
QPixmapCache::remove(currentFileDetails.fileInfo.absoluteFilePath());
```
In general, I am trying to get back to state after starting qView when no file is opened. :)

**Comment by jurplel** [comment]
Not exactly sure what it could be. Couple of things to try maybe:
- Try to make a qfile object and then call remove on it
- See if it works when you switch files first

I'm on vacation right now, but once I get back I can try to find the exact problem.

**Comment by artemanufrij** [comment]
BTW: I would move the file into trash an not remove it instantly

**Comment by pawel5** [comment]
@artemanufrij good idea, but trash support for Qt is currently in progress: https://bugreports.qt.io/browse/QTBUG-47703 so it would probably require some other library to use.

**Comment by AndydeCleyre** [comment]
If it's within the realm of possibility to detect presence of an external command and enable the feature only in that case, it's worth noting that [trash-cli](https://github.com/andreafrancia/trash-cli) while unchanged since 2017 is packaged by [many distros[(https://repology.org/project/trash-cli/versions) (in addition to PyPI).

**Comment by mlvnt** [comment]
Looks like https://bugreports.qt.io/browse/QTBUG-47703 is gonna be fixed in qt 5.15

**Comment by jurplel** [comment]
Nice to see, but I am planning to create my own solution that is compatible at least back to Qt 5.9

**Comment by ben2talk** [comment]
> Sure thing, I'll do it next version.

Please - version 4.0 I still have issues deleting files if I invoke qView from dupeguru - I then need to open a folder to delete a file.
Thus qView fails to be default.

**Comment by brunetton** [comment]
Any news on this ? I'm waiting for this to replace Gthumb. 
Thanks

**Comment by jurplel** [comment]
It is still a work in progress. Hopefully soon!

**Comment by cyclism6486** [comment]
Not sure how, but I have use the app "JustLooking" (and have for years) and it has always allowed the DEL key to delete the current file you're looking at.  The only problem why I can't continue to use JustLooking into the future is that it's a 32 bit app and support stopped for it a long time ago.  Get this feature in qView and I could finally abandon JustLooking.  I hope it's close! Thanks!

**Comment by jurplel** [comment]
Here's the plan:
Linux and mac will have fallback codepaths to delete files using the terminal, because they may be using older qt versions.

All platforms will have the new QFile::moveToTrash api as the primary method if it is available. Using this API, there will also be a function to undo deletion of a file using ctrl+z.

**Comment by Scobee** [comment]
@jurplel been waiting for this for a long time. This would make qView AMAZING. 
Looks like you already have it figured out.
Can't wait to see it in action!

**Comment by jurplel** [comment]
Still to-do:
- [x] Linux fallback (gio)
- [x] Hiding if incompatible
- [ ] mac fallback (https://developer.apple.com/documentation/appkit/nsworkspace/1530465-recycleurls)
- [ ] confirmation dialog/other usability suggestions maybe

**Comment by AndydeCleyre** [comment]
If it's not already happening, it might be nice to have a notification or something to alert that (1) something was deleted and (2) how to undo it (if possible).

When there's a confirmation dialog, I'd hope to be able to disable it, at least for the remainder of the current session.

**Comment by jurplel** [comment]
Yeah, I am unsure how exactly I will approach this, but my favorite idea so far is a confirmation dialog with a checkbox to never ask (with that option accessible in settings)

**Comment by cyclism6486** [comment]
Sounds like a perfect solution.

**Comment by jurplel** [comment]
@cyclism6486  Appreciate the feedback!

**Comment by jurplel** [comment]
Feel free to test for yourself with the link provided on https://github.com/jurplel/qView/pull/427
