### ISSUE TITLE
Shortcuts for "sort files by"

### ISSUE THREAD

**Issue by Digitt6** [jurplel/qView#814]
I'm constantly switching between random sort vs date created sort, and sometimes also want to change the sorting between asceending and descending

It'd be a huge help if changing the sorting mode could exist in the shortcuts section so we can configure shortcuts for it.

Ideally:

- a shortcut to cycle through the sort modes
- a shortcut to toggle ascending vs descending
- very ideal: seperate shortcuts for each mode (random, date created etc.)

Thank you

**Comment by mozzel** [comment]
I came here today to add my own request for this feature, but instead I found a kindred spirit.
I’d also really love shortcut for cycling sort modes, it would make qView much smoother to use in my workflow.

**Comment by jdpurcell** [comment]
I am not the author of qView but I maintain a fork of it. Another idea I'll mention which I implemented a while ago - I find it handy to be able to change sorting via the context menu:
<img width="320" height="293" alt="Image" src="https://github.com/user-attachments/assets/fb3d7cda-89a8-48d5-8440-84a0fa7879db" />

This is a temporary, per-window setting. Basically, when you open a new window, it defaults to whatever the global setting is (the one configured in the Settings dialog). Then you can change it in the context menu, which only applies to that one window, and doesn't change the global setting. Lastly if you do change the global setting, it will reset/change the sort mode for all open windows.

Perhaps not exactly what you were looking for (i.e. keyboard shortcuts), but convenient nonetheless.

**Comment by Digitt6** [comment]
thanks alot for this. i tried it and while its still not as ideal as a shortcut, it saves 1 step. 

 instead of qview - settings - change dropdown - click ok. it's context menu, hover over "sort by", choose setting

so thank you, it helps a bit for now

if you do end up working on the next build, it'd be a huge help to have the shortcut implemented. perhaps AI can cover the workload? thank you in advance. and thank you for your fork
